/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedNotificationsRouteImport } from './routes/_authenticated/notifications'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedJobsRouteImport } from './routes/_authenticated/jobs'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/_admin/route'
import { Route as AuthenticatedShipmentsNewRouteImport } from './routes/_authenticated/shipments.new'
import { Route as AuthenticatedShipmentsIdRouteImport } from './routes/_authenticated/shipments.$id'
import { Route as AuthenticatedAdminAdminUsersRouteImport } from './routes/_authenticated/_admin/admin.users'
import { Route as AuthenticatedAdminAdminTransportersRouteImport } from './routes/_authenticated/_admin/admin.transporters'
import { Route as AuthenticatedAdminAdminShipmentsRouteImport } from './routes/_authenticated/_admin/admin.shipments'
import { Route as AuthenticatedAdminAdminDisputesRouteImport } from './routes/_authenticated/_admin/admin.disputes'
import { Route as AuthenticatedAdminAdminDashboardRouteImport } from './routes/_authenticated/_admin/admin.dashboard'
import { Route as AuthenticatedAdminAdminBidsRouteImport } from './routes/_authenticated/_admin/admin.bids'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedNotificationsRoute =
  AuthenticatedNotificationsRouteImport.update({
    id: '/notifications',
    path: '/notifications',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedJobsRoute = AuthenticatedJobsRouteImport.update({
  id: '/jobs',
  path: '/jobs',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/_admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedShipmentsNewRoute =
  AuthenticatedShipmentsNewRouteImport.update({
    id: '/shipments/new',
    path: '/shipments/new',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedShipmentsIdRoute =
  AuthenticatedShipmentsIdRouteImport.update({
    id: '/shipments/$id',
    path: '/shipments/$id',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminAdminUsersRoute =
  AuthenticatedAdminAdminUsersRouteImport.update({
    id: '/admin/users',
    path: '/admin/users',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminTransportersRoute =
  AuthenticatedAdminAdminTransportersRouteImport.update({
    id: '/admin/transporters',
    path: '/admin/transporters',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminShipmentsRoute =
  AuthenticatedAdminAdminShipmentsRouteImport.update({
    id: '/admin/shipments',
    path: '/admin/shipments',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminDisputesRoute =
  AuthenticatedAdminAdminDisputesRouteImport.update({
    id: '/admin/disputes',
    path: '/admin/disputes',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminDashboardRoute =
  AuthenticatedAdminAdminDashboardRouteImport.update({
    id: '/admin/dashboard',
    path: '/admin/dashboard',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const AuthenticatedAdminAdminBidsRoute =
  AuthenticatedAdminAdminBidsRouteImport.update({
    id: '/admin/bids',
    path: '/admin/bids',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/admin/bids': typeof AuthenticatedAdminAdminBidsRoute
  '/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRoute
  '/admin/disputes': typeof AuthenticatedAdminAdminDisputesRoute
  '/admin/shipments': typeof AuthenticatedAdminAdminShipmentsRoute
  '/admin/transporters': typeof AuthenticatedAdminAdminTransportersRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/jobs': typeof AuthenticatedJobsRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/notifications': typeof AuthenticatedNotificationsRoute
  '/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/admin/bids': typeof AuthenticatedAdminAdminBidsRoute
  '/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRoute
  '/admin/disputes': typeof AuthenticatedAdminAdminDisputesRoute
  '/admin/shipments': typeof AuthenticatedAdminAdminShipmentsRoute
  '/admin/transporters': typeof AuthenticatedAdminAdminTransportersRoute
  '/admin/users': typeof AuthenticatedAdminAdminUsersRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/_admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/jobs': typeof AuthenticatedJobsRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/notifications': typeof AuthenticatedNotificationsRoute
  '/_authenticated/shipments/$id': typeof AuthenticatedShipmentsIdRoute
  '/_authenticated/shipments/new': typeof AuthenticatedShipmentsNewRoute
  '/_authenticated/_admin/admin/bids': typeof AuthenticatedAdminAdminBidsRoute
  '/_authenticated/_admin/admin/dashboard': typeof AuthenticatedAdminAdminDashboardRoute
  '/_authenticated/_admin/admin/disputes': typeof AuthenticatedAdminAdminDisputesRoute
  '/_authenticated/_admin/admin/shipments': typeof AuthenticatedAdminAdminShipmentsRoute
  '/_authenticated/_admin/admin/transporters': typeof AuthenticatedAdminAdminTransportersRoute
  '/_authenticated/_admin/admin/users': typeof AuthenticatedAdminAdminUsersRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/jobs'
    | '/marketplace'
    | '/notifications'
    | '/shipments/$id'
    | '/shipments/new'
    | '/admin/bids'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/shipments'
    | '/admin/transporters'
    | '/admin/users'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/dashboard'
    | '/jobs'
    | '/marketplace'
    | '/notifications'
    | '/shipments/$id'
    | '/shipments/new'
    | '/admin/bids'
    | '/admin/dashboard'
    | '/admin/disputes'
    | '/admin/shipments'
    | '/admin/transporters'
    | '/admin/users'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/_admin'
    | '/_authenticated/dashboard'
    | '/_authenticated/jobs'
    | '/_authenticated/marketplace'
    | '/_authenticated/notifications'
    | '/_authenticated/shipments/$id'
    | '/_authenticated/shipments/new'
    | '/_authenticated/_admin/admin/bids'
    | '/_authenticated/_admin/admin/dashboard'
    | '/_authenticated/_admin/admin/disputes'
    | '/_authenticated/_admin/admin/shipments'
    | '/_authenticated/_admin/admin/transporters'
    | '/_authenticated/_admin/admin/users'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/notifications': {
      id: '/_authenticated/notifications'
      path: '/notifications'
      fullPath: '/notifications'
      preLoaderRoute: typeof AuthenticatedNotificationsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/jobs': {
      id: '/_authenticated/jobs'
      path: '/jobs'
      fullPath: '/jobs'
      preLoaderRoute: typeof AuthenticatedJobsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin': {
      id: '/_authenticated/_admin'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipments/new': {
      id: '/_authenticated/shipments/new'
      path: '/shipments/new'
      fullPath: '/shipments/new'
      preLoaderRoute: typeof AuthenticatedShipmentsNewRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/shipments/$id': {
      id: '/_authenticated/shipments/$id'
      path: '/shipments/$id'
      fullPath: '/shipments/$id'
      preLoaderRoute: typeof AuthenticatedShipmentsIdRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/_admin/admin/users': {
      id: '/_authenticated/_admin/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AuthenticatedAdminAdminUsersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/transporters': {
      id: '/_authenticated/_admin/admin/transporters'
      path: '/admin/transporters'
      fullPath: '/admin/transporters'
      preLoaderRoute: typeof AuthenticatedAdminAdminTransportersRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/shipments': {
      id: '/_authenticated/_admin/admin/shipments'
      path: '/admin/shipments'
      fullPath: '/admin/shipments'
      preLoaderRoute: typeof AuthenticatedAdminAdminShipmentsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/disputes': {
      id: '/_authenticated/_admin/admin/disputes'
      path: '/admin/disputes'
      fullPath: '/admin/disputes'
      preLoaderRoute: typeof AuthenticatedAdminAdminDisputesRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/dashboard': {
      id: '/_authenticated/_admin/admin/dashboard'
      path: '/admin/dashboard'
      fullPath: '/admin/dashboard'
      preLoaderRoute: typeof AuthenticatedAdminAdminDashboardRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/_authenticated/_admin/admin/bids': {
      id: '/_authenticated/_admin/admin/bids'
      path: '/admin/bids'
      fullPath: '/admin/bids'
      preLoaderRoute: typeof AuthenticatedAdminAdminBidsRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminAdminBidsRoute: typeof AuthenticatedAdminAdminBidsRoute
  AuthenticatedAdminAdminDashboardRoute: typeof AuthenticatedAdminAdminDashboardRoute
  AuthenticatedAdminAdminDisputesRoute: typeof AuthenticatedAdminAdminDisputesRoute
  AuthenticatedAdminAdminShipmentsRoute: typeof AuthenticatedAdminAdminShipmentsRoute
  AuthenticatedAdminAdminTransportersRoute: typeof AuthenticatedAdminAdminTransportersRoute
  AuthenticatedAdminAdminUsersRoute: typeof AuthenticatedAdminAdminUsersRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminAdminBidsRoute: AuthenticatedAdminAdminBidsRoute,
    AuthenticatedAdminAdminDashboardRoute:
      AuthenticatedAdminAdminDashboardRoute,
    AuthenticatedAdminAdminDisputesRoute: AuthenticatedAdminAdminDisputesRoute,
    AuthenticatedAdminAdminShipmentsRoute:
      AuthenticatedAdminAdminShipmentsRoute,
    AuthenticatedAdminAdminTransportersRoute:
      AuthenticatedAdminAdminTransportersRoute,
    AuthenticatedAdminAdminUsersRoute: AuthenticatedAdminAdminUsersRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedJobsRoute: typeof AuthenticatedJobsRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedNotificationsRoute: typeof AuthenticatedNotificationsRoute
  AuthenticatedShipmentsIdRoute: typeof AuthenticatedShipmentsIdRoute
  AuthenticatedShipmentsNewRoute: typeof AuthenticatedShipmentsNewRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedJobsRoute: AuthenticatedJobsRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedNotificationsRoute: AuthenticatedNotificationsRoute,
  AuthenticatedShipmentsIdRoute: AuthenticatedShipmentsIdRoute,
  AuthenticatedShipmentsNewRoute: AuthenticatedShipmentsNewRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
